
_genres=[
    "Alternative",
    "Punk",
    "Anime",
    "Blues",
    "Acoustic Blues",
    "Chicago Blues",
    "Classic Blues",
    "Classic Female Blues",
    "Contemporary Blues",
    "Country Blues",
    "Delta Blues",
    "Electric Blues",
    "Folk Blues",
    "Harmonica Blues",
    "Jazz Blues",
    "Jump Blues",
    "Memphis Blues",
    "Modern Blues",
    "New Orlean Blues",
    "NY Blues",
    "Piano Blues",
    "Ragtime Blues",
    "Rhythm Blues",
    "Soul Blues",
    "Swamp Blues",
    "Texas Blues",
    "Urban Blues",
    "Vandeville",
    "Children’s Music",
    "Lullabies",
    "Sing-Along",
    "Stories",
    "Classical",
    "Avant-Garde",
    "Baroque",
    "Chamber Music",
    "Chant",
    "Choral",
    "Classical Crossover",
    "Early Music",
    "Expressionist",
    "High Classical",
    "Impressionist",
    "Medieval",
    "Minimalism",
    "Modern Composition",
    "Opera",
    "Orchestral",
    "Renaissance",
    "Wedding Music",
    "Comedy",
    "Novelty",
    "Standup Comedy",
    "Jingles",
    "TV Themes",
    "Country",
    "Alternative Country",
    "Americana",
    "Bluegrass",
    "Dance",
    "Breakcore",
    "Brostep",
    "Chillstep",
    "Deep House",
    "Dubstep",
    "Electro House",
    "Electroswing",
    "Garage",
    "Disney",
    "Electronic",
    "Ambient",
    "Drum & Bass",
    "Electronic Rock",
    "Hardstyle",
    "Trip Hop",
    "French Pop",
    "German Folk",
    "German Pop",
    "Hip-Hop/Rap",
    "Alternative Rap",
    "Gangsta Rap",
    "Hardcore Rap",
    "Hip-Hop",
    "Latin Rap",
    "Old School Rap",
    "Rap",
    "Holiday",
    "Chanukah",
    "Christmas",
    "Instrumental",
    "J-Pop",
    "J-Rock",
    "J-Synth",
    "J-Ska",
    "J-Punk",
    "Jazz",
    "Acid Jazz",
    "Avant-Garde Jazz",
    "Contemporary Jazz",
    "Cool",
    "Crossover Jazz",
    "Fusion",
    "Gypsy Jazz",
    "Latin Jazz",
    "Mainstream Jazz",
    "Smooth Jazz",
    "Latin",
    "Alternativo & Rock Latino",
    "Argentine tango",
    "Baladas & Boleros",
    "Bossa Nova",
    "Brazilian",
    "Cumbia",
    "Flamenco",
    "Portuguese fado",
    "Raíces",
    "Reggaeton",
    "Salsa",
    "Relaxation",
    "Opera",
    "Pop",
    "Funk",
    "Modern Soul",
    "Soul",
    "Reggae",
    "Roots Reggae",
    "Ska",
    "Rock",
    "Acid Rock",
    "Afro Punk",
    "Blues-Rock",
    "British Invasion",
    "Death Metal",
    "Black Metal"
    "Glam Rock",
    "Hair Metal",
    "Hard Rock",
    "Metal",
    "Metal Core",
    "Psychedelic",
    "Rock & Roll",
    "Singer/Songwriter",
    "Stoner Metal",
    "Surf",
    "Indie Folk",
    "Folk-Rock",
    "New Acoustic",
    "Traditional Folk",
    "Musicals",
    "Chicano",
    "Classic",
    "A cappella",
    "Vocal Jazz",
    "Vocal Pop",
    "World",
    "Africa",
    "Afro-Beat",
    "Afro-Pop",
    "Asia",
    "Cajun",
    "Indian Ghazal",
    "Indian Pop",
    "Japanese Pop",
    "Middle East",
    "Ode",
    "Piphat",
    "Soca"
]
_instruments=[
    "12-string guitar",
    "42-string Pikasa guitar",
	"Accordion",
    "Acoustic Guitar",
	"Acoustic Bass Guitar",
	"Alto Clarinet",
	"Alto Flute",
	"Alto Horn",
	"Alto Recorder",
	"Alto Sax",
	"Alto Trombone",
	"Argol",
	"Arranger",
	"Autoharp",
	"Backing Vocals",
	"Bagpipes",
	"Bandoneon",
	"Banjo",
	"Bansuri Flute",
	"Baritone Sax",
	"Bass",
	"Bass Clarinet",
	"Bass Drum",
	"Bass Flute",
	"Bass Harmonica",
	"Bass Recorder",
	"Bass Sax",
	"Bass Trombone",
	"Bass Trumpet",
	"Bassett Horn",
	"Bassoon",
	"Batá Drums",
	"Bells/Glockenspiel",
	"Berimbau",
	"Bird Whistle",
	"Bongos",
	"Bouzouki",
	"C-Melody Sax",
	"Cabasa/Afuche",
	"Cajon",
	"Castanets",
	"Celeste",
	"Chapman Stick",
	"Chekere/Shaker",
	"Cheng",
	"Chimes (Tubular Bells)",
	"Clarinet",
	"Claves",
	"Clavinet",
	"Conch Shells",
	"Conductor",
	"Congas",
	"Contrabass",
    "Contrabass Sarrusophone",
	"Contrabass Clarinet",
    "Contrabass Trombone",
	"Contrabass Saxophone",
    "Contralto Clarinet",
	"Contrabassoon",
	"Cornet",
    "Crotales",
	"Cowbell",
	"Cuatro",
	"Cymbals",
	"Dance",
	"Didgeridoo",
	"Director",
	"Doumbek",
    "Doussn'gouni (Hunter's Guitar)",
	"Drums",
	"Dulcimer",
	"Electric Bass",
	"Electric Guitar",
	"Electric Organ",
	"Electric Piano",
	"Electric Upright Bass",
	"Electronic Valve Instrument",
	"Electronic Wind Instrument",
	"English Horn",
	"Euphonium",
	"Finger Cymbals",
	"Flügelhorn",
	"Flute",
	"Frame Drum",
	"French Horn",
	"Gaita Colombian)",
	"Ghatam",
	"Gong",
	"Goofus/Cuesnophone",
	"Guiro",
	"Guitar",
	"Hag'houge/Gembri",
	"Handclaps",
	"Harmonica",
	"Harmonium",
	"Harp",
	"Harpsichord",
	"Hot Fountain Pen",
	"Kalimba/Mbira",
	"Karkaba",
	"Kazoo",
	"Keyboards",
	"Kora",
	"Koto",
	"Leader",
	"Lute",
	"Mandola",
	"Mandolin",
	"Manzello",
	"Maracas",
	"Marimba",
	"Master of Ceremonies",
	"Mellophone",
	"Mellophonium",
	"Melodica",
	"Mridangam",
	"Musette",
	"Musical Saw",
	"NED Synclavier",
	"Oboe",
	"Ocarina",
	"Other",
	"Oud",
	"Pan Flute",
	"Penny Whistle",
    "Piano",
	"Percussion",
    "Piccolo Bass",
	"Piccolov",
	"Piccolo Trumpet",
	"Pipe Organ",
	"Prepared Piano",
	"Programming Synth/Drum Machine",
	"Rabab",
	"Rap",
	"Recorder",
	"Sarod",
	"Sarrusophone",
	"Saxello",
	"Saz",
	"Shakuhachi Flute",
	"Shawm",
	"Shenai",
	"Sitar",
	"Sleigh Bells",
	"Slide Guitar",
	"Slide Saxophone",
	"Slide Trumpet",
	"Slide Whistle",
	"Snare Drum",
	"Sopranino Clarinet",
	"Sopranino Saxophone",
	"Soprano Recorder",
	"Soprano Sax",
	"Speaking",
	"Steel Drums",
	"Steel Guitar",
	"Strings",
	"Stritch",
	"Synthesizer",
	"Tablas",
	"Tamboura",
	"Tambourine",
	"Tarogato",
	"Tenor Drum",
	"Tenor Horn",
    "Tenor Sax",
	"Tenor Recorder",
	"Theremin",
	"Timbales",
	"Timpani",
	"Tiple",
	"Triangle",
	"Trombone",
	"Trombonium",
	"Trumpet",
	"Tuba",
	"Turntable/Electronics",
	"Ukelele",
	"Valve Trombone",
	"Vibraphone",
	"Viola",
	"Viola da Gamba",
	"Violin",
	"Violoncello",
	"Vitar",
	"Vocals",
	"Washboard",
	"Waterphone",
	"Whistling",
	"Wood Flute",
	"Woodblock",
	"Woodwinds",
	"Xylophone",
    "Zither"
]

def _find(value, lst):
    if value == '':
        return []

    vls = value.split()

    suggestions=[]
    for v in lst:
        all=True
        for j in vls:
            if not(j.lower() in v.lower()):
                all=False
                break
        if all:
            suggestions.append(v)

    return suggestions


def suggest_genres(value):
    return _find(value, _genres)

def suggest_instruments(value):
    return _find(value, _instruments)



from functools import wraps
from django.shortcuts import reverse, redirect
from django.http import HttpResponseBadRequest

def has_not_artist_profile(function):
    """
    A view function decorator that test whether the user requesting the corresponding URL has an artistprofile.
    If the user has a profile, the user will be redirect to it's artist profile page.
    We assume that the user is authenticated. Otherwise we automatically assume the user has no Aritst profile.
    """
    @wraps(function)
    def wrap(request, *args, **kwargs):

        if request.user.has_artistProfile():
            return redirect('artists:artist-profile', profile_id=request.user.get_artist().pk)
        else:
            return function(request, *args, **kwargs)
    return wrap


def has_artist_profile(function):
    """
    A view function decorator that test whether the user requesting the corresponding URL has an artistprofile.
    If the user has not a profile, the user will receive bad request.
    We assume the user is authenticated.
    """
    @wraps(function)
    def wrap(request, *args, **kwargs):

        if request.user.has_artistProfile():
            return function(request, *args, **kwargs)
        else:
            return HttpResponseBadRequest(content="This request can't be accesed if you don't have an artist profile")
    return wrap
